export const questionTypes = {
  NORMAL_MATH_RIDDLE: "NORMAL_MATH_EQUATION",
  TEXT_MATH_RIDDLE: "TEXT_MATH_RIDDLE",
  NUMBER_MEMORY_RIDDLE: "NUMBER_MEMORY_RIDDLE",
  COLOR_MEMORY_RIDDLE: "COLOR_MEMORY_RIDDLE",
  RANDOM: "RANDOM",
  ADMIN: "ADMIN",
};

export const answerTypes = {
  SHORT_ANSWER: "SHORT_ANSWER",
  MULTIPLE_CHOICE: "MULTIPLE_CHOICE",
};
